### PR TITLE
Cmake defines

### PR DESCRIPTION
**Pull request by ipdemes**
Added "ENABLE_LEGION_TLS" to the legion_defines

### CODE REVIEW

**Comment by lightsighter** [comment]
@ipdemes The ENABLE_LEGION_TLS feature is still experimental until we've done some more benchmarking on the performance overhead that it incurs.  I'll keep this pull request around until we decide whether we want to make it part of the mainline Legion master branch or not.

**Comment by ipdemes** [comment]
@lightsighter , I think we need to have this logic in legion_defines as long as you have "#ifdef ENABLE_LEGION_TLS" anywhere in the source code. Otherwise cmake would be broken for those who need this option to be ON. And you can always revert this commit in case you decide to remove LEGION_TLS from the legion src.

**Comment by lightsighter** [comment]
Yes, @streichler has informed me of my ignorance of cmake. :)  Merging the pull request.

**Comment by ipdemes** [comment]
@lightsighter , Thank you!!

**Comment by elliottslaughter** [comment]
@ipdemes If you're done with the branch, can you delete it? (There is button in this thread, or you can run `git push origin --delete cmake_defines`.)

**Comment by ipdemes** [comment]
@elliottslaughter , Sure. It should be removed now

**Pull request merged**
