### PR TITLE
Fix typos in documentation.

### PR DESCRIPTION
**Pull request by elliottslaughter**
I would appreciate it if someone could tell me whether I'm reading this documentation correctly...

### CODE REVIEW

**Comment by streichler** [comment]
Can't read it on my phone.  Will check from laptop in a few hours.

**Comment by elliottslaughter** [comment]
Just FYI: These changes are all for the `create_partition_by_image` function, not preimage.

**Comment by lightsighter** [comment]
Yes, I think all your changes are correct.  You can go ahead and commit this.

**Comment by streichler** [comment]
Yes, these changes look right.  The index space being partitioned is `handle`, and `parent` may be a logical region whose index space is an ancestor of `handle`.  Merging despite Travis' confusion.

**Pull request merged**
