### PR TITLE
Regent: fix bug in equal partition codegen

### PR DESCRIPTION
**Pull request by rupanshusoi**
Fix for #943

### CODE REVIEW

**Comment by elliottslaughter** [comment]
Would it be possible to get a test case that verifies the fix (i.e. fails without it, and passes with it)?

Otherwise everything looks good.

Thanks.

**Comment by rupanshusoi** [comment]
@elliottslaughter Done.

**Comment by elliottslaughter** [comment]
Actually this test fails for me. After a bit of digging, it looks like Regent is actually using two different code paths in the compiler. You can see this with a slightly modified test:

```
import "regent"

task main()
  -- Case 1. unstructured partitioned by 3D
  var r = region(ispace(ptr, 10), int)
  var p = partition(equal, r, ispace(int3d, {5, 5, 5}))

  -- Case 2. 1D partitioned by 3D
  var s = region(ispace(int1d, 10), int)
  var q = partition(equal, s, ispace(int3d, {5, 5, 5}))
end
regentlib.start(main)
```

Case 1 passes (with the patch) but case 2 fails.

It seems that case 2 is failing because we tried to set up a custom code path to make the equal partition output more sane in the case of multi-dimensional regions. But I'm not honestly sure if that makes sense when the region and color space dimensionality don't match. So maybe we should just fall back to the runtime equal partition in both cases.

**Comment by rupanshusoi** [comment]
Hmm, this test does not fail for me. I'm using an older commit, but for Regent it should be equivalent to the latest master.

**Comment by rupanshusoi** [comment]
@elliottslaughter I tested with the latest master, and your test did **not** fail for me. I do see CI failing for the new test I added (again, which seems to works fine for me), so not completely sure what's going on.

**Comment by elliottslaughter** [comment]
I went back to your original commit (on the theory that the merge might have gone bad), but it's still failing for me.

Do you have Sapling access? That's where I'm able to reproduce this.

**Comment by rupanshusoi** [comment]
@elliottslaughter Something weird is happening. I made a fresh clone on Sapling, built the latest master and applied this PR with `git pull origin pull/945/head`. The snippet you posted above did **not** fail for me.

> Case 1 passes (with the patch) but case 2 fails.

I think the changes in this PR aren't being applied for you (and for CI), because case 1 should work without this PR as well.

Can you please apply the patch I've attached and check if your code snippet still fails? I'm confident that it will work.
[patch.txt](https://github.com/StanfordLegion/legion/files/5496674/patch.txt)

**Comment by elliottslaughter** [comment]
I have rebased and pushed this to branch `regent-pr-945` at Gitlab. If it passes CI there then I'm inclined to merge it.

**Comment by elliottslaughter** [comment]
You can watch the tests run at https://gitlab.com/StanfordLegion/legion/-/pipelines/245762333/builds

**Comment by elliottslaughter** [comment]
I'm still getting a failure in CI, see e.g.: https://gitlab.com/StanfordLegion/legion/-/jobs/981724141

**Comment by lightsighter** [comment]
This is almost certainly a compiler/application bug. It's saying the type of the index space data passed in does not match the type of the index space handle.

**Comment by rupanshusoi** [comment]
I'm not sure if this is worth pointing out, but I could only get the error to reproduce on Sapling on installing with `--spy`. I can see similar behaviour with CI, where it passed with Spy disabled: https://gitlab.com/StanfordLegion/legion/-/jobs/981724142

Does this tell us anything useful?

**Comment by lightsighter** [comment]
I can reproduce the same failure after building Regent without Legion Spy support. Did you make sure you built Legion in debug mode with `--debug`? You won't hit this assertion in a release mode because Legion removes all assertions in release mode. Looking at the assertion below though, this is definitely the compiler's fault.

The part I don't understand is why Regent is invoking 'legion_create_partition_by_restriction' at all since this is a request to create an equal partition. If you're going to call `legion_create_partition_by_restriction` at all, then the second dimension of the transform must have the same dimensionality as the color space (in this case 3). However, the transform being passed into 'legion_create_partition_by_restriction` here has dimensionality 1x1. It should really be 1x3.

**Comment by elliottslaughter** [comment]
I pushed a rebase and final fix to https://gitlab.com/StanfordLegion/legion/-/tree/regent-pr-945. This will hopefully take care of it. While reading the code, I realized that what we had really only would work if `dim == color_dim`, because it was assuming we could block out each dimension one at a time. So now we only follow that code path if that's going to work, and fall back to the runtime otherwise.

**Comment by elliottslaughter** [comment]
This has been merged. Thanks!

**Pull request closed without merging**
