### PR TITLE
FindHWLOC.cmake: fix syntax error

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by streichler** [comment]
@junghans can you change this pull request to point at master instead of stable?

**Comment by streichler** [comment]
@chuckatkins please let me know if you have any concerns about this

**Comment by junghans** [comment]
Nice, github implemented that feature just in time:
https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by junghans** [comment]
Ping @chuckatkins

**Comment by junghans** [comment]
@streichler: we should add a test case to the ci running `cmake -DLegion_USE_HWLOC=ON`.

**Comment by chuckatkins** [comment]
+1

**Comment by junghans** [comment]
@streichler : I think this can be merged!

**Pull request merged**
