### PR TITLE
Regent: support for terra bit operations

### PR DESCRIPTION
**Pull request by rupanshusoi**
Fix for #867. I've tried to replicate the order of operations from C (which is what the intent already seems to be) but it does not always match with Terra. For example, `5 ^ 3 << 2` evaluates to `9` in Regent (with this PR) and C, but `24` in Terra.

### CODE REVIEW

**Comment by elliottslaughter** [comment]
It's unfortunate that Terra and C don't agree, I didn't realize that. In the past we've chosen to match Terra rather than C. But in this case it may be better to just throw an error when there's an inconsistency (i.e. the user has a `^` and a `<<` without parens to disambiguate). At least that way you won't get caught by surprise.

@streichler and I have been talking and we think it's possible to do this by marking all AST nodes surrounded by `()` with a special attribute (e.g. `has_parens`) and then we can check later on whether a `^` has as a child a `<<` with `has_parens == false` or vice versa.

Does that make sense?

**Comment by rupanshusoi** [comment]
Right, although I think I'll need some help with the implementation.

**Comment by elliottslaughter** [comment]
Step 1 would be to add the `has_parens` field to the unspecialized expr AST: https://github.com/StanfordLegion/legion/blob/master/language/src/regent/ast.t#L168

After that you have to modify the parser so that it sets `has_parens` to `false` for all AST nodes by default. (This is probably the most tedious step.)

At that point, you can modify the parser for `()` expressions. Instead of just returning `expr` you can return `expr` with `has_parens` set to true: https://github.com/StanfordLegion/legion/blob/master/language/src/regent/parser.t#L492

Then, finally you can write the check. This could go in a couple of places, but probably most straightforward would be to put it the parser itself in `expr_binary_left`: https://github.com/StanfordLegion/legion/blob/master/language/src/regent/parser.t#L1590

Let me know if you have any questions.

**Comment by rupanshusoi** [comment]
@elliottslaughter Please review.

**Comment by elliottslaughter** [comment]
This has been merged with aded2409d389ad0f72201c1da85193d64ac3d014. Thanks!

**Pull request closed without merging**
