### PR TITLE
Added "-D__STDC_FORMAT_MACROS" flag to the cmake build system. Appare…

### PR DESCRIPTION
**Pull request by ipdemes**
…ntly we need this flag to get Legion built on some systems

### CODE REVIEW

**Comment by ipdemes** [comment]
This is related to the issue:
https://github.com/StanfordLegion/legion/issues/181

**Comment by streichler** [comment]
@ipdemes : I don't think this will work.  On the systems with this issue, this define must be set before
the first #include of inttypes.h, which may come before any legion header is parsed in an application
that includes other headers.  I'm pretty sure it needs to be on the compilation command line for
application source files to work in all cases.

**Comment by junghans** [comment]
I think legion should define `__STDC_FORMAT_MACROS` in the headers, which use `inttype.h` and friends.

**Comment by streichler** [comment]
@junghans That's what we started with.  It works as long as the application code that is including legion.h hasn't already included inttypes.h (directly or indirectly).  The `__STDC_FORMAT_MACROS` macro must be defined before the first include of inttypes.h, no matter where it is, and a command line parameter is the only way to guarantee that.

**Comment by junghans** [comment]
You could error out if ` _INTTYPES_H` is defined without `__STDC_FORMAT_MACROS` before including `inttypes.h` in `runtime/legion/legion_utilities.h`. Something like:
```
#ifndef __STDC_FORMAT_MACROS
#ifdef  _INTTYPES_H
#error Legion need to be build with -D__STDC_FORMAT_MACROS
#endif
#else
#define __STDC_FORMAT_MACROS
#endif
#include <inttypes.h>
```

Plus, with all these defines legion really needs a pkg-config file.

**Comment by ipdemes** [comment]
@streichler, @junghans  : this commit actually fixes an error we see without __STDC_FORMAT_MACROS on one of our clusters (Darwin). I think this works because legion_defines.h gets included before any other legion header file is included.  I have just double-checked it this morning.

**Comment by streichler** [comment]
I'll merge this for now, but it sounds like you're just getting lucky.  I'll look into fixing it "right"
(i.e. eliminating the need for this define in application code at all, unless it also uses the format
macros).

**Comment by ipdemes** [comment]
@streichler : thank you. Do you have any test/example in legion that might  break? I can try  to check it out with cmake.

**Pull request merged**
