### PR TITLE
Processor sets

### PR DESCRIPTION
**Pull request by zard49**
Support for launching Kokkos or OpenMP tasks from inside of legion. There were 2 main changes:

1) Add a new processor type to realm to handle "sets" of processors.

2) Update the default mapper to use these ProcessorSets.

### CODE REVIEW

**Comment by lightsighter** [comment]
I'm ok with merging this if @streichler is.  We should probably merge into the master branch though.

**Comment by streichler** [comment]
@zard49: yes, can you switch this pull request to the master branch?  (I think github just added that functionality.)

**Comment by zard49** [comment]
It looks like it is already setup for master, what am I missing?

**Comment by streichler** [comment]
I guess it is.  I was just looking at mike's comment above mine.  :)
That said, can you close this and open a new pull request so that Travis gets another try to test it?
(The original pull request came along when we had brokenness in the tree, and Travis isn't smart enough
to re-try.)

**Pull request merged**
