### PR TITLE
added support to free resources associated with a processor group; th…

### PR DESCRIPTION
**Pull request by gabrieltanase42**
…is is usefull in applications where we create/destroy lots of processors groups

### CODE REVIEW

**Comment by gabrieltanase42** [comment]
This is the fix to address:
https://github.com/StanfordLegion/legion/issues/849

**Comment by lightsighter** [comment]
One thing that might be good would be to move this over to a merge request on gitlab since our github repo is just a clone, so all code merges are performed over there.

**Comment by streichler** [comment]
> One thing that might be good would be to move this over to a merge request on gitlab since our github repo is just a clone, so all code merges are performed over there.

No need.  I'm going to create a "real" branch for this because it needs a few tweaks before it can go in.

**Comment by streichler** [comment]
Closing this as it has been incorporated as part of the changes discussed in #849.

**Pull request closed without merging**
