### PR TITLE
cmake: realm/timers.cc need -fno-strict-aliasing

### PR DESCRIPTION
**Pull request by junghans**
This was discovered in #168.

### CODE REVIEW

**Comment by streichler** [comment]
@junghans Actually, can we just set this for all Legion source files?  There's several other places where type-punning goes on, and I'm not sure why g++ only complained about that one file.

**Comment by junghans** [comment]
Done!

**Comment by junghans** [comment]
@chuckatkins please let me know if you have any concerns about this

**Comment by streichler** [comment]
I was just waiting on Travis for this one...  :)

**Pull request merged**
