### PR TITLE
cmake: -lrt is not needed on APPLE

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by streichler** [comment]
Hi, thanks for the pull request.  The 'cmake' branch is slated to be deleted, as a slightly different implementation of a cmake-based build flow was chosen instead, and is currently in the master branch.  Could you take a look at whether this issue exists there, and if so, submit a new pull request for the master branch?  Thanks!

**Comment by junghans** [comment]
@ipdemes : Can we use the other branch in flecsi-third-party@dcf100bc4d4f5d912e9a47ef1eef4f72896a9e92 ?

**Comment by ipdemes** [comment]
Hi Christoph, do you mean "stable  branch" for legion?
If yes, I will try if it works with flecsi  (it wasn't really few month ago) and let you know.

Best,

Irina

**Comment by junghans** [comment]
Stable sounds good!

**Comment by streichler** [comment]
@ipdemes actually, master would be better than stable
They're pretty similar at the moment, but we like to take the pull requests into master if at all possible.

**Comment by ipdemes** [comment]
Ok, I'll try master then.
Christoph, how urgent do you need that? Can this wait until the next week?

Best,

Irina

**Comment by junghans** [comment]
Not urgent for me, but maybe @timmah

**Comment by ipdemes** [comment]
Ok, I'll try to do this  sooner.
Best,

Irina

**Pull request merged**
