### PR TITLE
CMake: Add version info to project and libraries

### LINKED ISSUE #175: Shared libraries miss an so version
cmake doesn't define an so version for the shared libs.

I will submit a pull-request shortly.

### PR DESCRIPTION
**Pull request by chuckatkins**
Closes #175

### CODE REVIEW

**Comment by chuckatkins** [comment]
@junghans are you good with this?

**Comment by chuckatkins** [comment]
Just using one of VERSION or SOVERSION will copy the value to both properties.  If we want to separately track stable APIs with an SOVERSION different than VERSION then we can certainly do that later but at the moment it seems that each release is binary-and API incompatible with the previous.

**Comment by streichler** [comment]
@chuckatkins Using our Legion "version number" in this way is likely to cause folks to assume we're using semantic versioning, which isn't the case.  I'd like to keep the SOVERSION distinct from our release labeling.

**Comment by chuckatkins** [comment]
AFAIK there's no expectation of ABI compatibility right?  If two builds have the same SOVERSION then the expectation is that they are ABI compatible, which is not currently the case from one "release" to the next.  Keeping a distinctly separate SOVERSION that needs to be explicitly changed every release just seemed like unnecessary overhead since the release version is changing anyways, hence why I made it the same as the release version.

Or am I misunderstanding the release process and there is actually a stable ABI to set SOVERSION to?

**Comment by streichler** [comment]
Hmm...  My point is that e.g. versions 16.05.0 and 16.06.0 are not API compatible, which would confuse somebody who thought 16 was the "major" version number.  You're absolutely right though that a constant value of 1 for SOVERSION doesn't really work either, but if there are other tools that expect to see some number there, at least it creates a number we can start consciously incrementing once our API-incompatible changes become less frequent.

**Comment by chuckatkins** [comment]
I don't believe that anything particularly needs it.  @junghans What was the motivation for setting SOVERSION in the first place?  If there's nothing meaningful to set it to then I'd argue for just keeping it empty entirely rather than a constant.

**Comment by chuckatkins** [comment]
With CMake in particuler, VERISON is used for the actual library name and SOVERSION is used for symlinking.  So, in this case, setting the VERSION property to the actual version and SOVERSION to 1 gives us:
```
       14 Sep 29 15:30 liblegion.so -> liblegion.so.1
       19 Sep 29 15:30 liblegion.so.1 -> liblegion.so.16.8.0
 67732584 Sep 29 15:30 liblegion.so.16.8.0
       13 Sep 29 15:30 librealm.so -> librealm.so.1
       18 Sep 29 15:30 librealm.so.1 -> librealm.so.16.8.0
 21958888 Sep 29 15:30 librealm.so.16.8.0
```
with the SONAME being set in the library to `liblegion.so.1` and `librealm.so.1`, which is what will actually get linked to and searched for at runtime.

**Comment by chuckatkins** [comment]
The implications for the different options are

1. Leave both VERSION and SOVERSION empty:
  - `liblegion.so` is the only file created
  - Applications link to `liblegion.so` at compile time.
  - Applications look for `liblegion.so` at runtime
2.  Set VERSION and leave SOVERSION empty (which implicitly sets SOVERSION to VERSION)
  - `liblegion.so.16.8.0` is created with the symlink `liblegion.so -> liblegion.so.16.8.0`
  - Applications link to `liblegion.so` at compile time
  - And applications explicitly look for `liblegion.so.16.8.0` at runtime.
3.  Set VERSION to release version and SONAME to something arbitrary, like `1`
  - `liblegion.so.16.8.0` is created with the symlinks `liblegion.so.1 -> liblegion.so.16.8.0` and `liblegion.so.1 -> liblegion.so.16.8.0`
  - Applications link to `liblegion.so` and compile time.
  - And applications explicitly look for `liblegion.so.1` at runtime.

**Comment by chuckatkins** [comment]
@streichler, @junghans given the various versioning options, any thoughts on how you'd like version information to be expressed in the library files?

**Comment by streichler** [comment]
I think I'd prefer to go back to having VERSION and SOVERSION both empty.  The issue with having to remember to bump the SOVERSION applies to the VERSION as well.

**Comment by chuckatkins** [comment]
Replaced by #191

**Pull request closed without merging**
