### PR TITLE
CMake port of Legion using newer CMake features for target usage requirements

### PR DESCRIPTION
**Pull request by chuckatkins**

### CODE REVIEW

**Comment by chuckatkins** [comment]
Thanks for the merge!  I'll get another PR up in the next day or two with specific documentation on how to use it.

**Comment by elliottslaughter** [comment]
@chuckatkins Is there a PPA for CMake for Ubuntu 14.04? Looks like the version in the Ubuntu package archive is 2.8, which isn't new enough to use with your build files.

**Comment by elliottslaughter** [comment]
When I build with `-DLegion_USE_GASNet=ON`, I get the following errors. This is on a machine where the GASNet location is defined by the environment variable `GASNET_ROOT`.

```
CMake Error at cmake/FindGASNet.cmake:120 (list):
  list sub-command REMOVE_ITEM requires list to be present.
Call Stack (most recent call first):
  cmake/FindGASNet.cmake:199 (_GASNet_create_component_target)
  CMakeLists.txt:70 (find_package)

CMake Error at cmake/FindGASNet.cmake:120 (list):
  list sub-command REMOVE_ITEM requires list to be present.
Call Stack (most recent call first):
  cmake/FindGASNet.cmake:199 (_GASNet_create_component_target)
  CMakeLists.txt:70 (find_package)

CMake Error at cmake/FindGASNet.cmake:120 (list):
  list sub-command REMOVE_ITEM requires list to be present.
Call Stack (most recent call first):
  cmake/FindGASNet.cmake:199 (_GASNet_create_component_target)
  CMakeLists.txt:70 (find_package)

CMake Error at cmake/FindGASNet.cmake:120 (list):
  list sub-command REMOVE_ITEM requires list to be present.
Call Stack (most recent call first):
  cmake/FindGASNet.cmake:199 (_GASNet_create_component_target)
  CMakeLists.txt:70 (find_package)

CMake Error at cmake/FindGASNet.cmake:120 (list):
  list sub-command REMOVE_ITEM requires list to be present.
Call Stack (most recent call first):
  cmake/FindGASNet.cmake:199 (_GASNet_create_component_target)
  CMakeLists.txt:70 (find_package)

CMake Error at cmake/FindGASNet.cmake:120 (list):
  list sub-command REMOVE_ITEM requires list to be present.
Call Stack (most recent call first):
  cmake/FindGASNet.cmake:199 (_GASNet_create_component_target)
  CMakeLists.txt:70 (find_package)
```

**Comment by chuckatkins** [comment]
So, right now the FindGASNet module doesn't listen to the environment
variable so you'll need to specify
-DGASNet_ROOT_DIR=/path/to/gasnet/install on the cmake configure command
line.  Even still, it shouldn't be failing in such an obtuse way.  For now,
try passing the GASNet location in the way I mentioned while I get a fix
put in that will: a) use the GASNET_ROOT env var if present to mimic the
current make file behavior and b) crate a more graceful failure situation.

- Chuck

**Comment by elliottslaughter** [comment]
Hm, I still seem to see issues:

```
$ ls $GASNET_ROOT
bin  include  lib  share

$ cmake -DLegion_USE_GASNet=ON -DGASNet_ROOT_DIR="$GASNET_ROOT" ..
[ same error as before ]
```

**Comment by chuckatkins** [comment]
Hmm, so it appears the way GASNet is getting searched for is not compatible
with how your's is built.  Could you send me what version and configure
options of GASNet you have so I can try to reproduce it?

- Chuck

**Pull request merged**
