### PR TITLE
CMake: Fix missing link dependencies from GASNet MPI conduit

### PR DESCRIPTION
**Pull request by chuckatkins**

### CODE REVIEW

**Comment by chuckatkins** [comment]
@junghans @ipdemes This should fix the gasnet-mpi link error you both encountered.

**Comment by junghans** [comment]
@streichler : please merge!

**Comment by junghans** [comment]
@chuckatkins: This needs another tweak:
https://travis-ci.org/losalamos/flecsi-third-party/jobs/173976459#L2308
If `GASNET_LD` is something like`/usr/lib64/openmpi/bin//mpicc -fPIC` your check will fail....
(we need to build gasnet with `-fPIC` to support shared libs)

**Comment by chuckatkins** [comment]
@junghans, does this work for you?:

``` cmake
diff --git a/cmake/FindGASNet.cmake b/cmake/FindGASNet.cmake
index 86c75eb..5ef4d68 100644
--- a/cmake/FindGASNet.cmake
+++ b/cmake/FindGASNet.cmake
@@ -94,6 +94,7 @@ gasnet-libs:
       OUTPUT_VARIABLE _GASNet_LD
       OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET
     )
+    list(GET _GASNet_LD 0 _GASNet_LD)
     execute_process(
       COMMAND ${GASNet_MAKE_PROGRAM} -s -f ${_TEMP_MAKEFILE} gasnet-ldflags
       OUTPUT_VARIABLE _GASNet_LDFLAGS
```

**Comment by junghans** [comment]
Nope, losalamos/flecsi-third-party@9174aa945669b9e410700e38ff4a038377211e04 -> https://travis-ci.org/losalamos/flecsi-third-party/jobs/174066360#L2314

I guess we have to turn `_GASNet_LD` into a list first!

**Pull request merged**
