### PR TITLE
cmake: support multilib

### PR DESCRIPTION
**Pull request by junghans**
Most Linux distros put libraries into lib64 on amd64, so let's make it configurable.

### CODE REVIEW

**Comment by streichler** [comment]
@junghans can you change this pull request to point at master instead of stable?

**Comment by streichler** [comment]
@chuckatkins please let me know if you have any concerns about this

**Comment by junghans** [comment]
ping @chuckatkins

**Comment by chuckatkins** [comment]
Using the GNUInstallDirs module would give a more robust approach and handle more cases than you've accounted for here.  See https://cmake.org/cmake/help/v3.6/module/GNUInstallDirs.html .  Basically include it at the top level, then the install commands would look like:

```
install(TARGETS Foo
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
)
```

**Comment by junghans** [comment]
@chuckatkins: Done!

**Comment by junghans** [comment]
@chuckatkins: Please review again!

**Comment by streichler** [comment]
@chuckatkins I'm going to go ahead and merge this in the name of progress, but please do look it over when you get a chance?  Thanks!

**Comment by chuckatkins** [comment]
Yes, I'm sorry for the delay.  It's fine.  Please proceed.

----------
Chuck Atkins
Staff R&D Engineer, Scientific Computing
Kitware, Inc.
(518) 881-1183

**Pull request merged**
